# Generated by Django 3.2.18 on 2023-02-20 00:25

import logging

from django.core.exceptions import FieldError
from django.db import migrations

logger = logging.getLogger('inventree')


def fix_purchase_price(apps, schema_editor):
    """
    DISABLED: This function referenced the deleted 'order' module (PurchaseOrder).
    Purchase order functionality has been removed from the system.

    Original purpose: Data migration for fixing historical issue with StockItem.purchase_price field.
    Ref: https://github.com/inventree/InvenTree/pull/4373
    """
    # Function disabled - order module removed
    pass

    # Original code commented out:
    # StockItem = apps.get_model('stock', 'stockitem')

    # items = StockItem.objects.exclude(
    #     purchase_order=None
    # ).exclude(
    #     supplier_part=None
    # ).exclude(
    #     purchase_price=None
    # )

    # try:
    #     items = items.exclude(supplier_part__pack_size=1)
    # except FieldError:
    #     pass

    # n_updated = 0

    # for item in items:
    #     # Grab a reference to the associated PurchaseOrder
    #     # Trying to find an absolute match between this StockItem and an associated PurchaseOrderLineItem
    #     po = item.purchase_order
    #     for line in po.lines.all():
    #         # SupplierPart match
    #         if line.part == item.supplier_part:
    #             # Unit price matches original PurchaseOrder (and is thus incorrect)
    #             if item.purchase_price == line.purchase_price:
    #                 item.purchase_price /= item.supplier_part.pack_size
    #                 item.save()

    #                 n_updated += 1

    # if n_updated > 0:
    #     logger.info(f"Corrected purchase_price field for {n_updated} stock items.")


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0047_supplierpart_pack_size'),
        ('stock', '0093_auto_20230217_2140'),
    ]

    operations = [
        migrations.RunPython(
            fix_purchase_price,
            reverse_code=migrations.RunPython.noop,
        )
    ]
